version: '3.8'

services:
  zeepub-bot:
    image: ghcr.io/devil1210/zeepub-bot:latest
    # build: . # Uncomment to build locally
    container_name: zeepub_bot
    restart: always
    env_file:
      - .env
      # volumes:
      # - ./config:/app/config  # Only for development
      # - ./plugins:/app/plugins  # Only for development
      # Uncomment if you want to persist logs outside
      # - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
