version: '3.8'

services:
  zeepub-bot:
    # image: ghcr.io/devil1210/zeepub-bot:latest
    build: .
    container_name: zeepub_bot
    restart: always
    # ports:
    #   - "8000:8000"
    env_file:
      - .env
      # volumes:
      # - ./config:/app/config  # Only for development
      # - ./plugins:/app/plugins  # Only for development
      # Uncomment if you want to persist logs outside
      # - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    dns:
      - 8.8.8.8
      - 1.1.1.1

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: zeepub_tunnel
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - zeepub-bot
